// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CargoExpress.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "wip")]
    public partial class US03_RegistroDeGastosDeViajeFeature : object, Xunit.IClassFixture<US03_RegistroDeGastosDeViajeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "wip"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US03_RegistroGastosViaje.feature"
#line hidden
        
        public US03_RegistroDeGastosDeViajeFeature(US03_RegistroDeGastosDeViajeFeature.FixtureData fixtureData, CargoExpress_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "US03 - Registro de gastos de viaje", "    As a logistics management entrepreneur I want to record the expenses incurred" +
                    " during trips to maintain accurate records and keep my clients informed about th" +
                    "e costs associated with their services", ProgrammingLanguage.CSharp, new string[] {
                        "wip"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Register trip expenses successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "US03 - Registro de gastos de viaje")]
        [Xunit.TraitAttribute("Description", "Register trip expenses successfully")]
        [Xunit.TraitAttribute("Category", "US03")]
        [Xunit.TraitAttribute("Category", "Gastos")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        [Xunit.InlineDataAttribute("1", "150.00", "50.00", "80.00", new string[0])]
        [Xunit.InlineDataAttribute("2", "200.50", "75.00", "120.00", new string[0])]
        public virtual void RegisterTripExpensesSuccessfully(string tripId, string gasoline, string tolls, string perDiem, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "US03",
                    "Gastos",
                    "HappyPath"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("tripId", tripId);
            argumentsOfScenario.Add("gasoline", gasoline);
            argumentsOfScenario.Add("tolls", tolls);
            argumentsOfScenario.Add("perDiem", perDiem);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register trip expenses successfully", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given("the entrepreneur wants to register trip expenses in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
        testRunner.And(string.Format("there is a registered trip with ID {0}", tripId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 9
        testRunner.When("accesses the platform and selects the Registration section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 10
        testRunner.And("selects the option to register a new expense", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 11
        testRunner.And("enters the trip ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table10.AddRow(new string[] {
                            "Gasoline",
                            string.Format("{0}", gasoline)});
                table10.AddRow(new string[] {
                            "Tolls",
                            string.Format("{0}", tolls)});
                table10.AddRow(new string[] {
                            "PerDiem",
                            string.Format("{0}", perDiem)});
#line 12
        testRunner.And("fills the required expense fields:", ((string)(null)), table10, "And ");
#line hidden
#line 17
        testRunner.And("clicks on \"Register\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
        testRunner.Then("the entered data will be validated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
        testRunner.And("the trip expenses will be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register expenses with negative values")]
        [Xunit.TraitAttribute("FeatureTitle", "US03 - Registro de gastos de viaje")]
        [Xunit.TraitAttribute("Description", "Register expenses with negative values")]
        [Xunit.TraitAttribute("Category", "US03")]
        [Xunit.TraitAttribute("Category", "Gastos")]
        [Xunit.TraitAttribute("Category", "ErrorValidacion")]
        public virtual void RegisterExpensesWithNegativeValues()
        {
            string[] tagsOfScenario = new string[] {
                    "US03",
                    "Gastos",
                    "ErrorValidacion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register expenses with negative values", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
        testRunner.Given("the entrepreneur wants to register trip expenses in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table11.AddRow(new string[] {
                            "Gasoline",
                            "-50.00"});
                table11.AddRow(new string[] {
                            "Tolls",
                            "-10.00"});
#line 29
        testRunner.When("tries to register an expense with negative values", ((string)(null)), table11, "When ");
#line hidden
#line 33
        testRunner.Then("the expense will not be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
        testRunner.And("a message indicating values must be positive will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register expenses for non-existent trip")]
        [Xunit.TraitAttribute("FeatureTitle", "US03 - Registro de gastos de viaje")]
        [Xunit.TraitAttribute("Description", "Register expenses for non-existent trip")]
        [Xunit.TraitAttribute("Category", "US03")]
        [Xunit.TraitAttribute("Category", "Gastos")]
        [Xunit.TraitAttribute("Category", "ErrorViaje")]
        public virtual void RegisterExpensesForNon_ExistentTrip()
        {
            string[] tagsOfScenario = new string[] {
                    "US03",
                    "Gastos",
                    "ErrorViaje"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register expenses for non-existent trip", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 37
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
        testRunner.Given("the entrepreneur wants to register trip expenses in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 39
        testRunner.When("enters a non-existent trip ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
        testRunner.Then("the expense will not be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
        testRunner.And("a message indicating the trip does not exist will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                US03_RegistroDeGastosDeViajeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                US03_RegistroDeGastosDeViajeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
