// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CargoExpress.IntegrationTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "wip")]
    public partial class US07_RegistroDeDatosDeVehiculoFeature : object, Xunit.IClassFixture<US07_RegistroDeDatosDeVehiculoFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "wip"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "US07_RegistroVehiculo.feature"
#line hidden
        
        public US07_RegistroDeDatosDeVehiculoFeature(US07_RegistroDeDatosDeVehiculoFeature.FixtureData fixtureData, CargoExpress_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "US07 - Registro de datos de vehículo", "    As a logistics management entrepreneur I want to register my vehicles\' data t" +
                    "o keep track of the shipments they make", ProgrammingLanguage.CSharp, new string[] {
                        "wip"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Register vehicle data successfully")]
        [Xunit.TraitAttribute("FeatureTitle", "US07 - Registro de datos de vehículo")]
        [Xunit.TraitAttribute("Description", "Register vehicle data successfully")]
        [Xunit.TraitAttribute("Category", "US07")]
        [Xunit.TraitAttribute("Category", "Vehiculo")]
        [Xunit.TraitAttribute("Category", "HappyPath")]
        [Xunit.InlineDataAttribute("Volvo FH", "ABC-123", "DEF-456", "20000", "80", new string[0])]
        [Xunit.InlineDataAttribute("Scania R", "XYZ-789", "QRS-012", "18000", "75", new string[0])]
        public virtual void RegisterVehicleDataSuccessfully(string model, string plate, string tractorPlate, string maxLoad, string volume, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "US07",
                    "Vehiculo",
                    "HappyPath"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("model", model);
            argumentsOfScenario.Add("plate", plate);
            argumentsOfScenario.Add("tractorPlate", tractorPlate);
            argumentsOfScenario.Add("maxLoad", maxLoad);
            argumentsOfScenario.Add("volume", volume);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register vehicle data successfully", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 6
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 7
        testRunner.Given("the entrepreneur wants to register vehicle data in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 8
        testRunner.When("accesses the platform and selects the Registration section", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 9
        testRunner.And("selects the option to register a new vehicle", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table14.AddRow(new string[] {
                            "Model",
                            string.Format("{0}", model)});
                table14.AddRow(new string[] {
                            "Plate",
                            string.Format("{0}", plate)});
                table14.AddRow(new string[] {
                            "TractorPlate",
                            string.Format("{0}", tractorPlate)});
                table14.AddRow(new string[] {
                            "MaxLoad",
                            string.Format("{0}", maxLoad)});
                table14.AddRow(new string[] {
                            "Volume",
                            string.Format("{0}", volume)});
#line 10
        testRunner.And("fills the required fields:", ((string)(null)), table14, "And ");
#line hidden
#line 17
        testRunner.And("clicks on \"Register\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 18
        testRunner.Then("the entered data will be validated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 19
        testRunner.And("the vehicle data will be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register vehicle with duplicate plate")]
        [Xunit.TraitAttribute("FeatureTitle", "US07 - Registro de datos de vehículo")]
        [Xunit.TraitAttribute("Description", "Register vehicle with duplicate plate")]
        [Xunit.TraitAttribute("Category", "US07")]
        [Xunit.TraitAttribute("Category", "Vehiculo")]
        [Xunit.TraitAttribute("Category", "ErrorValidacion")]
        public virtual void RegisterVehicleWithDuplicatePlate()
        {
            string[] tagsOfScenario = new string[] {
                    "US07",
                    "Vehiculo",
                    "ErrorValidacion"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register vehicle with duplicate plate", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 27
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 28
        testRunner.Given("the entrepreneur wants to register vehicle data in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 29
        testRunner.And("there is already a registered vehicle with plate \"ABC-123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 30
        testRunner.When("tries to register a new vehicle with the same plate", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 31
        testRunner.Then("the vehicle will not be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 32
        testRunner.And("a message indicating the vehicle already exists will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Register vehicle with invalid max load")]
        [Xunit.TraitAttribute("FeatureTitle", "US07 - Registro de datos de vehículo")]
        [Xunit.TraitAttribute("Description", "Register vehicle with invalid max load")]
        [Xunit.TraitAttribute("Category", "US07")]
        [Xunit.TraitAttribute("Category", "Vehiculo")]
        [Xunit.TraitAttribute("Category", "ErrorCapacidad")]
        public virtual void RegisterVehicleWithInvalidMaxLoad()
        {
            string[] tagsOfScenario = new string[] {
                    "US07",
                    "Vehiculo",
                    "ErrorCapacidad"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Register vehicle with invalid max load", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 35
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 36
        testRunner.Given("the entrepreneur wants to register vehicle data in the application", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table15.AddRow(new string[] {
                            "MaxLoad",
                            "-1000"});
#line 37
        testRunner.When("enters a negative max load", ((string)(null)), table15, "When ");
#line hidden
#line 40
        testRunner.Then("the vehicle will not be registered", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
        testRunner.And("a message indicating max load must be positive will be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                US07_RegistroDeDatosDeVehiculoFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                US07_RegistroDeDatosDeVehiculoFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
